# Generated by Django 4.0.1 on 2022-03-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_check_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
