# Generated by Django 4.0.1 on 2022-03-01 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_check_app', '0002_alter_msg_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msg',
            old_name='id',
            new_name='num',
        ),
    ]
