# Generated by Django 4.0.1 on 2022-03-03 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_check_app', '0003_rename_id_msg_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msg',
            old_name='num',
            new_name='id',
        ),
    ]
